### ISSUE TITLE
Migrate Image to Python 3

### ISSUE THREAD

**Issue by Forger125** [linuxserver/docker-pyload#16]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

Sorry in advance for any faux pas with this post, it's my first bug for LSIO!

## Expected Behavior

Should the Docker image use the more recent Pyload version (Pyload-NG) built atop Python 3 (from branch "master") rather than the legacy version on Python 2 which is now EOL and deprecated per project documentation (from branch "stable").

## Current Behavior
The image is still built on Python 2 (see below)
![image](https://user-images.githubusercontent.com/786092/97815419-d1a84680-1c5b-11eb-9d59-35995d03f3be.png)

## Steps to Reproduce

NA

## Environment
**OS:** Ubuntu 18.04.5 
**CPU architecture:** arm64 (Raspberry Pi Model 4B)
**Image digest:** d6e4f904fda3a97045d98c520630dfcc66d24407de7d62b08a48d6e1bdcd9a82
**How docker service was installed:** Distro repo

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2.1"  
services:  
  pyload:  
    image: linuxserver/pyload  
    container_name: pyload  
    environment:  
      - PUID=1001  
      - PGID=1001  
      - TZ="America/New York"  
    volumes:  
      - ./config:/config  
      - /home/ubuntu/Downloads:/downloads  
    ports:  
      - 4444:8000  
    labels:  
      - "diun.enable=true"  
      - "diun.watch_repo=true"  
    restart: unless-stopped
```

## Docker logs
NA
