### ISSUE TITLE
Default login doesn't work

### ISSUE THREAD

**Issue by lorenzschmid** [linuxserver/docker-pyload#3]
Using the default parameter  indicated in the README file (user: `admin`, password:`password`) don't work. Reading in the [pyload wiki](https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(Linux)) I discovered that upon a first start, the user database isn't initalized and one has first to execute the following:

    docker exec -it [container_name, e.g. pyload] python /app/pyload/pyLoadCore.py -s

**Comment by j0nnymoe** [comment]
Please post your docker compose/run info. We've not experienced this issue in testing.

**Comment by lorenzschmid** [comment]
There you go:

```
version: '3'
services:
  pyload:
    image: linuxserver/pyload
    container_name: pyload
    environment:
      - PGID=100
      - PUID=1028
      - TZ=Europe/Zurich
    volumes:
      - /volume/download/pyload/:/config
      - /volume/tmp/pyload/:/downloads
    restart: unless-stopped
    networks:
      - download_net
```
